export const copy = {
  es: {
    skip: "Saltar al contenido",
    nav: [
      "Inicio",
      "Experiencia",
      "Proyectos",
      "Sobre mí",
      "Educación",
      "Contacto",
    ],
    heroEyebrow: "Software Developer · Argentina",
    heroTitle:
      "Construyo y gestiono soluciones empresariales con Power Platform, .NET y React.",
    heroText:
      "Combino desarrollo de software, liderazgo operativo y pensamiento de producto para convertir necesidades complejas en soluciones claras y mantenibles.",
    availability: "Actualmente trabajando · abierto a nuevas oportunidades",
    viewExperience: "Ver experiencia",
    contact: "Contactarme",
    downloadCv: "Descargar CV",
    cvUnavailable: "CV en inglés pendiente",
    focus: "Áreas y tecnologías",
    focusItems: [
      [
        "Soluciones empresariales",
        "Power Apps, automatización y aplicaciones corporativas centradas en procesos reales.",
        ["Power Apps", "Power Automate", "SharePoint"],
      ],
      [
        "Frontend",
        "Interfaces web y extensiones empresariales con componentes tipados y mantenibles.",
        ["React", "TypeScript", "Angular", "SPFx"],
      ],
      [
        "Backend y datos",
        "APIs, persistencia e integraciones orientadas a resolver flujos completos.",
        [".NET", "ASP.NET Core", "Node.js", "SQL"],
      ],
      [
        "Plataforma y entrega",
        "Herramientas para colaborar, automatizar y sostener la evolución de las soluciones.",
        ["Azure", "Git", "Azure DevOps", "PowerShell"],
      ],
    ],
    projects: "Proyectos",
    projectsLead: "Casos con contexto, decisiones y contribuciones concretas.",
    caseStudy: "Ver caso de estudio",
    caseStudyLabel: "Caso de estudio",
    projectDetails: "Ver detalle del proyecto",
    projectDetailsLabel: "Detalle del proyecto",
    demo: "Abrir demo",
    sourceCode: "Ver código",
    problem: "Problema",
    contribution: "Mi contribución",
    outcome: "Resultado y aprendizaje",
    evidence: "Evidencia visual",
    prototypeTitle: "Prototipo interactivo de ejemplo",
    prototypeLead: "Una demostración conceptual para explorar algunas interacciones. No es el proyecto final ni una reproducción exacta de su interfaz.",
    previewCase: "Vista previa del caso de estudio",
    previewProject: "Vista previa del proyecto",
    aiTransparency: "Transparencia sobre IA",
    stackAndProcess: "Tecnologías y proceso",
    explorePrototype: "Explorar prototipo interactivo",
    back: "Volver al portfolio",
    experience: "Experiencia",
    experienceLead:
      "De construir aplicaciones a coordinar su evolución junto a usuarios, análisis funcional y desarrollo.",
    current: "Marzo 2024 — actualidad",
    role: "Supervisor de Desarrollo y Desarrollador Power Platform",
    company: "Circo Studio · Proyectos para YPF",
    expSummary:
      "Participo en soluciones empresariales y actualmente lidero la gestión cotidiana de una aplicación corporativa transversal.",
    expBullets: [
      "Relevo pedidos con la persona usuaria cliente y análisis funcional, evalúo viabilidad y anticipo dependencias o riesgos.",
      "Estimo, organizo y delego tareas, acompañando la entrega dentro del equipo.",
      "Desarrollé un framework UX reutilizable para Power Apps junto al equipo de diseño, mejorando consistencia y reutilización.",
      "Capacito a ingresantes y delego evoluciones del framework, compartiendo criterios y buenas prácticas.",
    ],
    frameworkEyebrow: "Sistema de diseño · Power Apps",
    frameworkTitle: "Una base compartida para construir con consistencia.",
    frameworkText:
      "El framework organiza componentes, estilos y pantallas reutilizables. Lo desarrollé junto al equipo de UX y hoy también acompaño su adopción, evolución y transferencia dentro del equipo.",
    frameworkCards: [
      "Componentes reutilizables",
      "Pantallas estandarizadas",
      "Iconografía y patrones",
    ],
    frameworkLabel: "POWER APPS / SISTEMA DE DISEÑO",
    frameworkCaption:
      "Representación conceptual — sin interfaces ni información interna.",
    about: "Sobre mí",
    aboutParagraphs: [
      "Soy desarrollador de software con formación en desarrollo web y actualmente trabajo construyendo soluciones empresariales tanto en entornos low-code como de desarrollo tradicional.",
      "Me gusta involucrarme más allá de la implementación: entender el problema, pensar en la experiencia del usuario, construir soluciones reutilizables y buscar continuamente mejores formas de hacer las cosas.",
      "Soy una persona curiosa por naturaleza y disfruto aprender nuevas tecnologías, experimentar con ideas y convertirlas en soluciones prácticas. Integro la IA en ese proceso para explorar, desarrollar y validar con mayor rapidez, manteniendo bajo mi responsabilidad las decisiones técnicas, la calidad y los resultados.",
    ],
    education: "Educación",
    educationItems: [
      [
        "Licenciatura en Gestión de Tecnología",
        "Universidad Nacional de La Matanza",
        "2026–2027 · En curso",
      ],
      [
        "Tecnicatura Universitaria en Desarrollo Web",
        "Universidad Nacional de La Matanza",
        "2022–2025 · Promedio 8,6",
      ],
      ["Técnico en Electrónica", "Instituto San José (A-355)", "2014–2019"],
    ],
    additionalTraining: "Formación complementaria",
    dataScienceCourse: [
      "Curso de Data Science",
      "Universidad Tecnológica Nacional (UTN)",
      "Noviembre de 2024",
    ],
    credentialLink: "Ver credencial en LinkedIn",
    community: "Charlas y comunidad",
    communityLead:
      "Compartir lo aprendido también forma parte de construir soluciones con impacto.",
    communityLink: "Ver publicación en LinkedIn",
    communityItems: [
      [
        "WIRIN en la 23.ª Jornada sobre la Biblioteca Digital Universitaria",
        "Presentación académica en equipo sobre accesibilidad bibliográfica y el aprendizaje de resolver una necesidad real en un equipo multidisciplinario · UNLaM · noviembre de 2025",
        "https://www.linkedin.com/posts/ceditunlam_egresados-del-diit-en-la-23-jbdu-ugcPost-7399482208429948928-Wj7P",
      ],
      [
        "Charla en la Feria Educativa 2026",
        "Encuentro con estudiantes de escuelas secundarias para compartir, desde la experiencia personal, los primeros pasos profesionales y el aprendizaje dentro del Programa de Becas Tecnológicas del CEDIT.",
        "https://www.linkedin.com/posts/ceditunlam_charla-cedit-en-la-feria-educativa-2026-ugcPost-7454991014303342592-tqzs",
      ],
      [
        "Experiencia como becario tecnológico y graduado",
        "Testimonio sobre el crecimiento profesional, los desafíos y los aprendizajes que exceden lo puramente técnico durante el paso por el programa del CEDIT.",
        "https://www.linkedin.com/posts/ceditunlam_m%C3%A1s-que-una-beca-la-experiencia-cedit-ugcPost-7446915128865873920-rr0q",
      ],
      [
        "Graduación como Técnico Universitario en Desarrollo Web",
        "Reconocimiento del CEDIT a quienes completaron su formación universitaria durante el primer semestre de 2025.",
        "https://www.linkedin.com/posts/ceditunlam_nuestros-graduados-ugcPost-7368291401576382464-GQ0b",
      ],
    ],
    contactTitle: "Conversemos",
    contactLead:
      "Si mi perfil encaja con una oportunidad o proyecto, podés escribirme por email o LinkedIn.",
    name: "Nombre",
    email: "Email",
    subject: "Asunto",
    message: "Mensaje",
    send: "Enviar mensaje",
    sending: "Enviando…",
    sent: "Mensaje enviado correctamente.",
    prepared: "Email preparado en tu aplicación de correo.",
    sendError: "No se pudo enviar. Usá el enlace de email alternativo.",
    revealEmail: "Mostrar email",
    copyEmail: "Copiar email",
    copied: "Email copiado",
    required: "Este campo es obligatorio.",
    invalidEmail: "Ingresá un email válido.",
    privacy:
      "Los datos se usan únicamente para responder tu mensaje. Sin rastreo invasivo.",
    language: "Idioma",
    theme: "Tema",
    themes: ["Sistema", "Claro", "Oscuro"],
    footer:
      "Diseñado y desarrollado con foco en claridad, accesibilidad y mantenimiento.",
    ai: "Desarrollo asistido por IA",
  },
  en: {
    skip: "Skip to content",
    nav: ["Home", "Experience", "Projects", "About", "Education", "Contact"],
    heroEyebrow: "Software Developer · Argentina",
    heroTitle:
      "I build and manage enterprise solutions with Power Platform, .NET, and React.",
    heroText:
      "I combine software development, operational leadership, and product thinking to turn complex needs into clear, maintainable solutions.",
    availability: "Currently employed · open to new opportunities",
    viewExperience: "View experience",
    contact: "Contact me",
    downloadCv: "Download résumé",
    cvUnavailable: "English résumé pending",
    focus: "Areas and technologies",
    focusItems: [
      [
        "Enterprise solutions",
        "Power Apps, automation, and corporate applications grounded in real processes.",
        ["Power Apps", "Power Automate", "SharePoint"],
      ],
      [
        "Frontend",
        "Web interfaces and enterprise extensions built with typed, maintainable components.",
        ["React", "TypeScript", "Angular", "SPFx"],
      ],
      [
        "Backend and data",
        "APIs, persistence, and integrations designed around complete workflows.",
        [".NET", "ASP.NET Core", "Node.js", "SQL"],
      ],
      [
        "Platform and delivery",
        "Tools for collaboration, automation, and sustainable solution delivery.",
        ["Azure", "Git", "Azure DevOps", "PowerShell"],
      ],
    ],
    projects: "Projects",
    projectsLead:
      "Case studies with context, decisions, and concrete contributions.",
    caseStudy: "View case study",
    caseStudyLabel: "Case study",
    projectDetails: "View project details",
    projectDetailsLabel: "Project details",
    demo: "Open live demo",
    sourceCode: "View source",
    problem: "Problem",
    contribution: "My contribution",
    outcome: "Outcome and learning",
    evidence: "Visual evidence",
    prototypeTitle: "Interactive example prototype",
    prototypeLead: "A conceptual demonstration for exploring selected interactions. It is not the final project or an exact reproduction of its interface.",
    previewCase: "Case study preview",
    previewProject: "Project preview",
    aiTransparency: "AI transparency",
    stackAndProcess: "Technologies and process",
    explorePrototype: "Explore interactive prototype",
    back: "Back to portfolio",
    experience: "Experience",
    experienceLead:
      "From building applications to coordinating their evolution with users, functional analysis, and development.",
    current: "March 2024 — present",
    role: "Development Supervisor & Power Platform Developer",
    company: "Circo Studio · Projects for YPF",
    expSummary:
      "I contribute to enterprise solutions and currently lead the day-to-day management of a cross-company corporate application.",
    expBullets: [
      "Gather requests with the client user and functional analysis, assess feasibility, and anticipate dependencies or risks.",
      "Estimate, organize, and delegate tasks while supporting the team through delivery.",
      "Built a reusable Power Apps UX framework with the design team, improving consistency and reuse.",
      "Train new team members and delegate framework improvements, sharing standards and practices.",
    ],
    frameworkEyebrow: "Design system · Power Apps",
    frameworkTitle: "A shared foundation for consistent delivery.",
    frameworkText:
      "The framework organizes reusable components, styles, and screens. I built it with the UX team and now also support its adoption, evolution, and knowledge transfer across the team.",
    frameworkCards: [
      "Reusable components",
      "Standardized screens",
      "Iconography and patterns",
    ],
    frameworkLabel: "POWER APPS / DESIGN SYSTEM",
    frameworkCaption:
      "Conceptual representation — no internal interfaces or information.",
    about: "About me",
    aboutParagraphs: [
      "I’m a software developer with a web development background, currently building enterprise solutions across low-code and traditional development environments.",
      "I enjoy taking ownership beyond the implementation itself: understanding the problem, thinking through the user experience, building reusable solutions, and continuously improving how things are done.",
      "I’m naturally curious and enjoy learning new technologies, experimenting with ideas, and turning them into practical solutions. I use AI throughout that process to explore, build, and validate faster, while keeping technical decisions, quality, and outcomes under my responsibility.",
    ],
    education: "Education",
    educationItems: [
      [
        "Bachelor's Degree in Technology Management",
        "Universidad Nacional de La Matanza",
        "2026–2027 · In progress",
      ],
      [
        "University Degree in Web Development",
        "Universidad Nacional de La Matanza",
        "2022–2025 · GPA 8.6/10",
      ],
      ["Electronics Technician", "Instituto San José (A-355)", "2014–2019"],
    ],
    additionalTraining: "Additional training",
    dataScienceCourse: [
      "Data Science course",
      "National Technological University (UTN)",
      "November 2024",
    ],
    credentialLink: "View credential on LinkedIn",
    community: "Talks and community",
    communityLead:
      "Sharing what I learn is also part of building solutions with meaningful impact.",
    communityLink: "View post on LinkedIn",
    communityItems: [
      [
        "WIRIN at the 23rd University Digital Library Conference",
        "Team presentation on bibliographic accessibility and the lessons learned from addressing a real need within a multidisciplinary team · UNLaM · November 2025",
        "https://www.linkedin.com/posts/ceditunlam_egresados-del-diit-en-la-23-jbdu-ugcPost-7399482208429948928-Wj7P",
      ],
      [
        "Talk at the 2026 Education Fair",
        "A conversation with secondary-school students about early professional experience and continuous learning within CEDIT's Technology Scholarship Program.",
        "https://www.linkedin.com/posts/ceditunlam_charla-cedit-en-la-feria-educativa-2026-ugcPost-7454991014303342592-tqzs",
      ],
      [
        "Technology scholar and graduate experience",
        "A first-person account of professional growth, challenges, and the lessons that went beyond technical skills during the CEDIT program.",
        "https://www.linkedin.com/posts/ceditunlam_m%C3%A1s-que-una-beca-la-experiencia-cedit-ugcPost-7446915128865873920-rr0q",
      ],
      [
        "University Degree in Web Development graduation",
        "CEDIT recognition for scholarship recipients who completed their university education during the first half of 2025.",
        "https://www.linkedin.com/posts/ceditunlam_nuestros-graduados-ugcPost-7368291401576382464-GQ0b",
      ],
    ],
    contactTitle: "Let's talk",
    contactLead:
      "If my background fits an opportunity or project, reach out by email or LinkedIn.",
    name: "Name",
    email: "Email",
    subject: "Subject",
    message: "Message",
    send: "Send message",
    sending: "Sending…",
    sent: "Message sent successfully.",
    prepared: "Email prepared in your email application.",
    sendError: "The message could not be sent. Use the alternative email link.",
    revealEmail: "Show email",
    copyEmail: "Copy email",
    copied: "Email copied",
    required: "This field is required.",
    invalidEmail: "Enter a valid email address.",
    privacy:
      "Your data is only used to reply to your message. No invasive tracking.",
    language: "Language",
    theme: "Theme",
    themes: ["System", "Light", "Dark"],
    footer:
      "Designed and developed with clarity, accessibility, and maintainability in mind.",
    ai: "AI-assisted development",
  },
} as const;
